# Generated by Django 4.1.1 on 2022-09-17 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('numberPlayer', models.IntegerField(primary_key=True, serialize=False)),
                ('namePlayer', models.CharField(default='NAME', max_length=32)),
                ('birthday', models.DateField()),
                ('dateAdd', models.DateField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipos.teams')),
            ],
        ),
    ]
