# Generated by Django 4.1.1 on 2022-09-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teams',
            fields=[
                ('numberteam', models.IntegerField(primary_key=True, serialize=False)),
                ('nameTeam', models.CharField(default='Generic Team', max_length=32)),
                ('city', models.CharField(default='Generic City', max_length=18)),
                ('numberPlayers', models.IntegerField(default=0)),
                ('mascotname', models.CharField(default='Generic Mascot', max_length=32)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='equipos/')),
                ('motto', models.CharField(default='Without motto', max_length=200)),
                ('dateForge', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
