# Generated by Django 4.1.1 on 2022-09-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stadiums',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('nameStadium', models.CharField(default='Generic Stadium', max_length=32)),
                ('city', models.CharField(default='Generic City', max_length=18)),
                ('maxPersons', models.IntegerField(default=0)),
                ('nextGame', models.DateField()),
            ],
        ),
    ]
